base-url = "https://scpwiki.com/"

# SCP Articles
[[articles]]
name = "SCP-4339"
title = "The Attribute Pen"
snippet = "D-91386 was told to say \"my name is D-88111\".\nD-88111's identification was changed."

[[articles]]
name = "SCP-3597"
title = "Maladroit"
contest = ["cliche-con-2019", "Cliché-Con"]
snippet = "**Description:** [DATA EXPUNGED]"

[[articles]]
name = "SCP-4447"
title = "Sasha's Super Shuttle Service!"
snippet = "When the anomaly is activated, the individuals, including their clothing, attached equipment, and jewelry, immediately switch positions."

[[articles]]
name = "SCP-1294-J"
title = "Watering-down Can"
snippet = "Oak wood restraints painted cyan and reinforced with lead-telekill-iron-oxide alloy have been attached to the object to prevent spills."

[[articles]]
name = "SCP-4322"
title = "Sleepless Dreams"
snippet = "SCP-4322 is a radio transceiver, anomalously modified to transmit psionic waves instead of electromagnetic radiation."

[[articles]]
name = "SCP-4406"
title = "SUDDEN THUNDER"
co-authors = ["pxdnbluesoul"]
contest = ["collaboration-contest", "Collab-Con"]
snippet = "SCP-4406 is highly advanced surveillance software, which masks itself from the host operating system by means of an electronic antimeme."

[[articles]]
name = "SCP-4838"
title = "Lover's Quarrel"
snippet = "I know this is a hard time for us, but I truly do love you. We are strong, we'll make it through this."

[[articles]]
name = "SCP-4853"
title = "&SCP-4853"
title-override = "&**[[[SCP-4853]]]**"
snippet = "The only designation which may be applied to SCP-4853 is SCP-4853."

[[articles]]
name = "SCP-4781"
title = "Sour and Dill"
snippet = "Specimens of SCP-4781 exhibit a cognitohazardous effect, causing misidentification of the anomaly and its effects as non-anomalous dill pickles."

[[articles]]
name = "SCP-5900"
title = "PITCHBLACK"
contest = ["scp5000contesthub", "5k-Con"]
snippet = "During this time, surveillance satellites, Site-07 communications, intelligence processing, and IntSCPFN file sync were inoperable. The full extent and nature of the anomaly are presently unknown."

[[articles]]
name = "SCP-5633"
title = "This Will Require A Great Amount of Blood"
co-authors = [
    "Rex Atlas",
    "Captain Kirby",
    "JackalRelated",
    "magna2s",
    "Modulum",
    "Rounderhouse",
    "Sterbai",
    "Tufto",
    "Uncle Nicolini",
    "Woedenaz",
    "Yossipossi",
]
snippet = "SCP-5633 is a large humanoid body located approximately 50m underground. The inside of SCP-5633 consists of enlarged veins, and steel scaffolding. The veins contain liquid that is both red and black in coloration, and highly viscous. Pipes extracting liquid from SCP-5633's veins are located along its arms, legs and back."

[[articles]]
name = "SCP-5510"
title = "Universal Remote"
snippet = "Your session will expire after 118 seconds of inactivity."

[[articles]]
name = "SCP-5502"
title = "Where the Smoke Trail Ends"
contest = ["/forum/t-13863495/9th-annual-holiday-art-exchange", "2020 Art Exchange"]
snippet = "SCP-5502 refers to an event on 2034/05/05 at around 04:10 UTC wherein all Fifthist-related anomalies known to the Foundation became neutralized."

[[articles]]
name = "SCP-5134"
title = "Itchy"
snippet = "Consequently, any physical contact on an infected individual will permanently scrape off that area of bodily tissue."

[[articles]]
name = "SCP-5446"
title = "Shock Troops"
contest = ["jam-con-2021", "JamCon 2021"]
snippet = "Originally SCP-5446 was held in a Site-19 locker before being requisitioned to produce sea-based security personnel."

[[articles]]
name = "SCP-5871"
title = "Retroactive Knife"
contest = ["jam-con-2021", "JamCon 2021"]
snippet = "The object was discovered in an anomalous burial site within modern-day Mongolia in 1831 and was created in 2020."

[[articles]]
name = "SCP-6140"
title = "The True Empire"
slug = "scp-6140"
co-authors = ["stormbreath"]
contest = ["scp6000contesthub", "6k-Con"]
snippet = "Daevite control of nuclear weapons and ICBMs for delivery is a certainty."

[[articles]]
name = "SCP-6115"
title = "The Public Option"
slug = "scp-6115"
contest = ["/forum/t-14303381/10th-annual-holiday-art-exchange", "2021 Art Exchange"]
snippet = "This system does not utilize traditional boundaries between organs and bodily tissue, instead opting for an internal circulatory system within the confines of their body composed almost entirely of thaumaturgic medium fluids."

[[articles]]
name = "SCP-7200"
title = "boats."
slug = "scp-7200"
co-authors = ["smlt"]
contest = ["scp7000contesthub", "7k-Con"]
snippet = "SCP-7200 is an anomalous phenomenon causing the disappearances of non-military ships in international waters."

[[articles]]
name = "SCP-7558"
title = "Always Test Your Backups"
slug = "scp-7558"
snippet = "When activated, it opened a link to a stable pocket universe located at a fixed location (SCP-7558-A), with the goal that it would protect documents, records, and other materials against dimensional shifts and CK-Class Reality Restructuring Scenarios."

[[articles]]
name = "SCP-8998"
title = "Her Owner"
slug = "scp-8998"
contest = ["scp8000contesthub", "8k-Con"]
snippet = "This is contrary to behavior of other documented apex-tier pluripotent entities, which often engage in behaviors such as accruing worshippers, creating paranormal artifacts, or intervening to achieve certain outcomes. Instead, its primary interest seems to be in the well-being of itself and SCP-8998-1."

[[articles]]
name = "SCP-8178"
title = "The Quiet"
slug = "scp-8178"
snippet = "Specifically, such individuals become aware of the sounds and movements of TALLL[!-- sic --] entities."

# Tales
[[articles]]
type = "tale"
name = "The Heart of the Beast"
slug = "heart-of-the-beast"
contest = ["canon-renaissance-contest", "Canon Renaissance Contest"]
snippet = "Fae shook her head. \"I really don't know. But — at least we can make his last week here a happy one.\""

[[articles]]
type = "tale"
name = "The Pumpkin Mystery"
slug = "pumpkin-mystery"
contest = ["jam-con-2021", "JamCon 2021"]
snippet = "Early on the morning after, residents gathered in shock before the ruins of our Civic Center, surrounded by uprooted trees and shreds of pumpkins throughout the park."

[[articles]]
type = "tale"
name = "Stealing Something Else"
slug = "stealing-something-else"
contest = ["/forum/t-15388623/11th-annual-holiday-art-exchange", "2022 Art Exchange"]
snippet = "Foundation Area-529 is located underground on the island of Barentsøya, an officially-uninhabited island part of the Svalbard archipelago, which is considered to be part of Norway. It was created in 1958 to provide a sustainable containment solution for SCP-████-1 instances."

[[articles]]
type = "tale"
name = "Continuous Integration"
slug = "continuous-integration"
contest = ["/forum/t-16456604/12th-annual-art-exchange", "2023 Art Exchange"]
snippet = "\"You can't just rerun it until it passes. This isn't a web server, this is core infrastructure that powers the life and livelihood of two billion humans.\""

# GoI Formats
[[articles]]
type = "goi-format"
name = "UIU File: 2017-102"
title = "WHISPER IN THE WIND"
slug = "uiu-file-2017-102"
co-authors = ["pxdnbluesoul"]
contest = ["collaboration-contest", "Collab-Con"]
goi = ["unusual-incidents-unit", "Unusual Incidents Unit"]
snippet = "Once delivered to a host, WHISPER is capable of inspecting, modifying, and emptying the host's counters and registers at will."

# Hubs
[[articles]]
type = "hub"
name = "Finding Asmodeus"
slug = "finding-asmodeus-hub"
contest = ["canon-renaissance-contest", "Canon Renaissance Contest"]

# Author Page
[[articles]]
type = "author"
name = "aismallard's author page"
slug = "aismallard"

# Other
# (none)
